"""Added has_nuts bool

Revision ID: 5e09354cd9d2
Revises: 30a6a91f201e
Create Date: 2023-11-13 16:01:57.575348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e09354cd9d2'
down_revision: Union[str, None] = '30a6a91f201e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('has_nuts', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'has_nuts')
    # ### end Alembic commands ###
